env:
  global:
    - secure: XnnxSncPvHtQla09NrVySvd3oyc+wjaSMJPP0jqvCrdv6zUZKzf1Z+HFTrxSoA5SYU69n+u6icqllRIvHSCF2dZqrj3+YZ6Ie0f0x1zXCrJU368NnDvi22a7j0MIep8+4CMvZ1q3roxGO4wLc9YqXvI0sUb/7F3qdqMwdvkh8EiLOVhbOR1SjP6v/QWuvxjytQ8imFs+qDeEnt5gmFMaz7nO2aPmQBv7knCL7BI2b8KolPmLcGdSC/edebkhC/qV4Z2ImLaC0T36b7waX7VXCaAqif1jPezK9AL3Zl6tFdZbO0BWAR0e+ARIrg0QAALBiicXoYr037q8k6WJQB14NFL0Pmid2kfv4olZAAITpJo/4qQ6FCUEjczzxc//8ckg07j6KRT0N1g/Zr+M5anxI7n2XuFeX6bP7wdETS7/nypxo98hvGinqpRl+tBVLUSwFvEOqpgUhwFOjiBDwYLmMVjJNEVNvE6CyJxUKLCIXDrgtxkShZYdMdhjWOZflaJSm5pRSDf4FEDogq8YFT36YxbPFlLHngjsolcu+0/ev49JD5FjCsvKmPWy2ksiK16CNAs8/rtHpAWb8ISDM7Sys3HqRakwd03yvKflNGQMgai5V84usCUrxrcS2KDCmezz4KwhgQIyP84tz436/9Y7f+YgZjaIs2EZsVrS2XMsDYA=
    - Features=use-mock-routing
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - nightly
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - $HOME/libsodium
    - $HOME/elfutils
install:
  - curl -sSLO https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/install_libsodium.sh
  - . install_libsodium.sh
script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/build_and_run_tests.sh | bash
before_cache:
  - curl -sSLO https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/install_elfutils.sh
  - . install_elfutils.sh
after_success:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/after_success.sh | bash
