[package]
name          = "maidsafe_nfs"
version       = "0.0.1"
authors       = ["MaidSafe Developers <dev@maidsafe.net>"]
description   = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://maidsafe.net/maidsafe_nfs/latest"
repository    = "https://github.com/maidsafe/maidsafe_nfs"
readme        = "README.md"
license       = "GPL-3.0"
homepage      = "http://maidsafe.net"

[dependencies]
# ---- Maidsafe ----
routing         = "0.2.*"
self_encryption = "0.2.*"
#maidsafe_client = "*"

# ---- Others ----
cbor            = "*"
time            = "*"
sodiumoxide     = "*"
rustc-serialize = "*"

[dependencies.maidsafe_client]
git = "https://github.com/maidsafe/maidsafe_client.git"

[features]
USE_ACTUAL_ROUTING = ["maidsafe_client/USE_ACTUAL_ROUTING"]
